// subgraph api doesn't provide total count, so we use binary search to identify it
// generated by claude-san, modified by human
export async function getTotalCount<T>({
	fetchPage,
	batchSize,
	startSize = 1000,
}: {
	fetchPage: (offset: number) => Promise<T[]>;
	batchSize: number;
	startSize?: number;
}): Promise<number> {
	let left = 0;
	let right = startSize;

	// First, find an upper bound
	while (true) {
		const items = await fetchPage(right);
		if (items.length === 0) break;
		right *= 2;
	}

	// Binary search for the exact boundary
	while (left < right) {
		const mid = Math.floor(left + (right - left) / 2);
		// Round down to nearest page boundary
		const pageOffset = Math.floor(mid / batchSize) * batchSize;

		const items = await fetchPage(pageOffset);

		if (items.length === 0) {
			right = pageOffset;
		} else {
			left = pageOffset + batchSize;
		}
	}

	return left;
}
